### ISSUE TITLE
Setup some form of shared folders for Windows/Mac host and FreeBSD guest. 

### ISSUE THREAD

**Issue by rsnair2** [UIUCFreeBSD/UIUCFreeBSD#1]

**Comment by msaxena2** [comment]
Follow instructions on this [link](https://forums.freebsd.org/threads/howto-virtualbox-folder-sharing-os-x-host-freebsd-guest.44231/). Get back to me if you run into any trouble.

**Comment by rsnair2** [comment]
Solved.
